# Generated by Django 4.2.7 on 2023-11-25 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flava_flavs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='updated',
        ),
    ]
