# Generated by Django 4.2.7 on 2023-11-25 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flava_flavs', '0002_remove_fooditem_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='created',
        ),
    ]
