# Generated by Django 4.2.7 on 2023-11-26 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flava_flavs', '0003_remove_fooditem_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='created',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='flavor',
            name='created',
        ),
        migrations.RemoveField(
            model_name='flavor',
            name='updated',
        ),
    ]
