# Generated by Django 4.2.7 on 2023-11-26 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flava_flavs', '0004_remove_customer_created_remove_customer_updated_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Flavor',
        ),
    ]
